# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'showgui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1129, 854)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadButton.setGeometry(QtCore.QRect(120, 497, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.loadButton.setFont(font)
        self.loadButton.setObjectName("loadButton")
        self.imgLabel = QtWidgets.QLabel(self.centralwidget)
        self.imgLabel.setGeometry(QtCore.QRect(70, 160, 501, 311))
        self.imgLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.imgLabel.setText("")
        self.imgLabel.setObjectName("imgLabel")
        self.imgLabel2 = QtWidgets.QLabel(self.centralwidget)
        self.imgLabel2.setEnabled(True)
        self.imgLabel2.setGeometry(QtCore.QRect(600, 160, 501, 311))
        self.imgLabel2.setFrameShape(QtWidgets.QFrame.Box)
        self.imgLabel2.setText("")
        self.imgLabel2.setObjectName("imgLabel2")
        self.grayButton = QtWidgets.QPushButton(self.centralwidget)
        self.grayButton.setGeometry(QtCore.QRect(800, 500, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.grayButton.setFont(font)
        self.grayButton.setObjectName("grayButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1129, 26))
        self.menubar.setObjectName("menubar")
        self.menuOperasi_Ttik = QtWidgets.QMenu(self.menubar)
        self.menuOperasi_Ttik.setObjectName("menuOperasi_Ttik")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCitra_Keabuan = QtWidgets.QAction(MainWindow)
        self.actionCitra_Keabuan.setObjectName("actionCitra_Keabuan")
        self.actionCitra_Kecerahan = QtWidgets.QAction(MainWindow)
        self.actionCitra_Kecerahan.setObjectName("actionCitra_Kecerahan")
        self.actionCitra_Kontras = QtWidgets.QAction(MainWindow)
        self.actionCitra_Kontras.setObjectName("actionCitra_Kontras")
        self.actioncontrast_stretching = QtWidgets.QAction(MainWindow)
        self.actioncontrast_stretching.setObjectName("actioncontrast_stretching")
        self.actionCitra_Negative = QtWidgets.QAction(MainWindow)
        self.actionCitra_Negative.setObjectName("actionCitra_Negative")
        self.actionCitra_Biner = QtWidgets.QAction(MainWindow)
        self.actionCitra_Biner.setObjectName("actionCitra_Biner")
        self.menuOperasi_Ttik.addAction(self.actionCitra_Kecerahan)
        self.menuOperasi_Ttik.addAction(self.actionCitra_Kontras)
        self.menuOperasi_Ttik.addAction(self.actioncontrast_stretching)
        self.menuOperasi_Ttik.addAction(self.actionCitra_Negative)
        self.menuOperasi_Ttik.addAction(self.actionCitra_Biner)
        self.menubar.addAction(self.menuOperasi_Ttik.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loadButton.setText(_translate("MainWindow", "LOAD IMAGE"))
        self.grayButton.setText(_translate("MainWindow", "Citra Button"))
        self.menuOperasi_Ttik.setTitle(_translate("MainWindow", "Operasi Titik"))
        self.actionCitra_Keabuan.setText(_translate("MainWindow", "Citra Keabuan"))
        self.actionCitra_Kecerahan.setText(_translate("MainWindow", "Citra_kecerahan"))
        self.actionCitra_Kontras.setText(_translate("MainWindow", "Citra Kontras"))
        self.actioncontrast_stretching.setText(_translate("MainWindow", "Contrast Stretching"))
        self.actionCitra_Negative.setText(_translate("MainWindow", "Citra Negative"))
        self.actionCitra_Biner.setText(_translate("MainWindow", "Citra Biner"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
